package repository;

import cn.smart.dds.DataSource;

public interface CrudMapper<T, ID>{
	
	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_administrator
     *
     * @mbggenerated
     */
	@DataSource(DataSource.MASTER)
    int deleteByPrimaryKey(ID id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_administrator
     *
     * @mbggenerated
     */
	@DataSource(DataSource.MASTER)
    int insert(T record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_administrator
     *
     * @mbggenerated
     */
	@DataSource(DataSource.MASTER)
    int insertSelective(T record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_administrator
     *
     * @mbggenerated
     */
	@DataSource(DataSource.MASTER)
    T selectByPrimaryKey(ID id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_administrator
     *
     * @mbggenerated
     */
    @DataSource(DataSource.SLAVE)
    int updateByPrimaryKeySelective(T record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_administrator
     *
     * @mbggenerated
     */
    @DataSource(DataSource.MASTER)
    int updateByPrimaryKey(T record);
}
